{
  LOG.error("Unable to execute task.  Exception is ",t);
  task.exceptionThrown(t);
}
