{
  try {
    return executeTask();
  }
 catch (  Exception e) {
    exceptionThrown(e);
    throw new RuntimeException(e);
  }
}
